<?php

namespace Proxies\__CG__;

/**
 * THIS CLASS WAS GENERATED BY THE DOCTRINE ORM. DO NOT EDIT THIS FILE.
 */
class User extends \User implements \Doctrine\ORM\Proxy\Proxy
{
    private $_entityPersister;
    private $_identifier;
    public $__isInitialized__ = false;
    public function __construct($entityPersister, $identifier)
    {
        $this->_entityPersister = $entityPersister;
        $this->_identifier = $identifier;
    }
    /** @private */
    public function __load()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;

            if (method_exists($this, "__wakeup")) {
                // call this after __isInitialized__to avoid infinite recursion
                // but before loading to emulate what ClassMetadata::newInstance()
                // provides.
                $this->__wakeup();
            }

            if ($this->_entityPersister->load($this->_identifier, $this) === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            unset($this->_entityPersister, $this->_identifier);
        }
    }

    /** @private */
    public function __isInitialized()
    {
        return $this->__isInitialized__;
    }

    
    public function getId()
    {
        if ($this->__isInitialized__ === false) {
            return (int) $this->_identifier["id"];
        }
        $this->__load();
        return parent::getId();
    }

    public function setEmail($email)
    {
        $this->__load();
        return parent::setEmail($email);
    }

    public function getEmail()
    {
        $this->__load();
        return parent::getEmail();
    }

    public function setName($name)
    {
        $this->__load();
        return parent::setName($name);
    }

    public function getName()
    {
        $this->__load();
        return parent::getName();
    }

    public function toArray()
    {
        $this->__load();
        return parent::toArray();
    }

    public function getMail()
    {
        $this->__load();
        return parent::getMail();
    }

    public function setMail($str)
    {
        $this->__load();
        return parent::setMail($str);
    }

    public function getHash()
    {
        $this->__load();
        return parent::getHash();
    }

    public function setHash($password)
    {
        $this->__load();
        return parent::setHash($password);
    }

    public function setAdmin()
    {
        $this->__load();
        return parent::setAdmin();
    }

    public function setNormal()
    {
        $this->__load();
        return parent::setNormal();
    }

    public function isValid()
    {
        $this->__load();
        return parent::isValid();
    }

    public function isAdmin()
    {
        $this->__load();
        return parent::isAdmin();
    }

    public function login()
    {
        $this->__load();
        return parent::login();
    }

    public function logout()
    {
        $this->__load();
        return parent::logout();
    }

    public function getAdmin()
    {
        $this->__load();
        return parent::getAdmin();
    }

    public function setSessionId($session_id)
    {
        $this->__load();
        return parent::setSessionId($session_id);
    }

    public function getSessionId()
    {
        $this->__load();
        return parent::getSessionId();
    }

    public function updateActivity()
    {
        $this->__load();
        return parent::updateActivity();
    }

    public function setLastActivity($last_activity)
    {
        $this->__load();
        return parent::setLastActivity($last_activity);
    }

    public function getLastActivity()
    {
        $this->__load();
        return parent::getLastActivity();
    }

    public function save()
    {
        $this->__load();
        return parent::save();
    }

    public function delete()
    {
        $this->__load();
        return parent::delete();
    }

    public function getWSattr()
    {
        $this->__load();
        return parent::getWSattr();
    }

    public function __destruct()
    {
        $this->__load();
        return parent::__destruct();
    }


    public function __sleep()
    {
        return array('__isInitialized__', 'id', 'name', 'email', 'hash', 'admin', 'session_id', 'last_activity', 'favorites');
    }

    public function __clone()
    {
        if (!$this->__isInitialized__ && $this->_entityPersister) {
            $this->__isInitialized__ = true;
            $class = $this->_entityPersister->getClassMetadata();
            $original = $this->_entityPersister->load($this->_identifier);
            if ($original === null) {
                throw new \Doctrine\ORM\EntityNotFoundException();
            }
            foreach ($class->reflFields AS $field => $reflProperty) {
                $reflProperty->setValue($this, $reflProperty->getValue($original));
            }
            unset($this->_entityPersister, $this->_identifier);
        }
        
    }
}